// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgeejxmhrxrcxvzvvmhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZWVqeG1ocnhyY3h2enZ2bWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDk2NDQsImV4cCI6MjA2NTcyNTY0NH0.xfZ9WtNURZ4-8-Q9ZmN8yiiYtDAbVxKmMfqhr4H5ocM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);